name: Ollivanders
main: me.cakenggt.Ollivanders.Ollivanders
version: 0.04
author: cakenggt
commands:
  Okit:
    description: This command gives an op the starting kit.
    usage: Example usage /Okit
