#
# Configuration for the Ollivanders2 plugin.
#
# Details for configuring the Ollivanders2 plugin can be found on our wiki at https://github.com/Azami7/Ollivanders2/wiki/Configuration
#
# *** READ THE INSTRUCTIONS BEFORE CHANGING THE DEFAULT CONFIGURATION ***
#
# Some of the configurations below will alter your MC server. When in doubt, use the default config, which is
# always on the safe option.
#
# *** BACKUP OF YOUR SERVER BEFORE ALTERING CONFIGURATION ***
#
# This should be standard practice for any change you make to your server.

# Chat options
#
# https://github.com/Azami7/Ollivanders2/wiki/Configuration#chat
chatDropoff: 15
chatColor: 5
showLogInMessage: false

# Spell Casting
#
# https://github.com/Azami7/Ollivanders2/wiki/Configuration#spell-casting
bookLearning: true
nonVerbalSpellCasting: false
spellJournal: true
hostileMobAnimagi: false
deathExpLoss: false

# Houses
#
# https://github.com/Azami7/Ollivanders2/wiki/Configuration#houses-and-years
houses: false
years: false

# Magical Items
#
# https://github.com/Azami7/Ollivanders2/wiki/Configuration#magical-items
flooPowder: REDSTONE
broomstick: STICK
witchDrop: false

# Debug Mode
#
# Turns on debug output in your logs. This can also be toggled on and off in game by using the command
# /olli debug
debug: false

#
# Zones
#
# https://github.com/Azami7/Ollivanders2/wiki/Configuration#zones
zones:
  default-world:
    type: World
    world: world
    allowed-spells:
      - 
    disallowed-spells:
      - 
  default-cuboid:
    type: Cuboid
    world: world
    area: 0 0 0 0 0 0
    allowed-spells:
      - 
    disallowed-spells:
      - 