#
# Configuration for the Ollivanders2 plugin.
#
# Details for configuring the Ollivanders2 plugin can be found on our wiki at https://github.com/Azami7/Ollivanders2/wiki/Configuration
#
# *** READ THE INSTRUCTIONS BEFORE CHANGING THE DEFAULT CONFIGURATION ***
#
# Some of the configurations below will alter your MC server. When in doubt, use the default config, which is
# always on the safe option.
#
# *** BACKUP OF YOUR SERVER BEFORE ALTERING CONFIGURATION ***
#
# This should be standard practice for any change you make to your server.

# Chat options
#
# https://github.com/Azami7/Ollivanders2/wiki/Configuration#chat
chatDropoff: 15
chatColor: 5
showLogInMessage: false

# Spell Casting
#
# https://github.com/Azami7/Ollivanders2/wiki/Configuration#spell-casting
bookLearning: true
nonVerbalSpellCasting: false
spellJournal: true
hostileMobAnimagi: false
deathExpLoss: false

# Houses
#
# https://github.com/Azami7/Ollivanders2/wiki/Configuration#houses-and-years
houses: false
displayMessageOnSort: false
gryffindorName: "Gryffindor"
hufflepuffName: "Hufflepuff"
ravenclawName: "Ravenclaw"
slytherinName: "Slytherin"
gryffindorColor: DARK_RED
hufflepuffColor: GOLD
ravenclawColor: BLUE
slytherinColor: DARK_GREEN

# Years
#
# https://github.com/Azami7/Ollivanders2/wiki/Configuration#years
years: false

# Magical Items
#
# https://github.com/Azami7/Ollivanders2/wiki/Configuration#magical-items
flooPowder: REDSTONE
broomstick: STICK
witchDrop: false

# Divination
#
# https://github.com/Azami7/Ollivanders2/wiki/Configuration#divination
divinationMaxDays: 4

# Experimental and Debug options
#
# Turns on debug output in your logs. This can also be toggled on and off in game by using the command
# /olli debug
debug: false
#
# Override version checks. This will force the plugin to load regardless of MC api version.
# **IMPORTANT** Backup your plugins/Ollivanders2 directory before enabling this option - running unsupported versions may corrupt plugin data
overrideVersionCheck: false

#
# Zones
#
# https://github.com/Azami7/Ollivanders2/wiki/Configuration#zones
zones:
  default-world:
    type: World
    world: world
    allowed-spells:
      - 
    disallowed-spells:
      - 
  default-cuboid:
    type: Cuboid
    world: world
    area: 0 0 0 0 0 0
    allowed-spells:
      - 
    disallowed-spells:
      - 