name: Ollivanders2
main: net.pottercraft.Ollivanders2.Ollivanders2
version: 2.0
author: Azami7
commands:
  Okit:
    description: This command gives an op the starting kit.
    usage: Example usage /Okit
