name: Ollivanders2
main: net.pottercraft.Ollivanders2.Ollivanders2
version: 2.2.1
authors: [Azami7, Lil_Miss_Giggles]
website: https://www.spigotmc.org/resources/ollivanders2.38992/
commands:
  Okit:
    description: This command gives an op the starting kit.
    usage: Example usage /Okit

  Quidd:
    description: This command creates a Quidditch arena.
    usage: Example usage /Quidd Hogwarts
